config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"

  get "up" => "rails/health#show", as: :rails_health_check

  resource :dashboard, only: :show
  resource :fetch_rate, only: :create

  root "dashboards#show"
  mount Sidekiq::Web => "/sidekiq"
end

app/models/aevo.rb
class Aevo
  include NanosecondsConversion
  include HTTParty
  base_uri 'api.aevo.xyz'

  # returns the current funding rate for the instrument
  def funding(instrument)
    self.class.get("/funding", query: { instrument_name: "#{instrument}-PERP"})
  end

  def save_funding_rate(response, exchange, instrument)
    FundingRate.create!(
      rate: response["funding_rate"],
      expire_at: nanoseconds_to_time(response["next_epoch"]),
      exchange: exchange,
      instrument: instrument
    )
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/nanoseconds_conversion.rb
module NanosecondsConversion
  extend ActiveSupport::Concern

  def nanoseconds_to_time(nanoseconds)
    # Convert nanoseconds to seconds (float to maintain the fractional part)
    seconds = nanoseconds.to_i / 1_000_000_000.0

    # Convert seconds to a Time object
    Time.at(seconds).utc
  end

  def time_to_nanoseconds(datetime)
    time = Time.new(datetime.year, datetime.month, datetime.day, datetime.hour, datetime.min, datetime.sec)

    # Get seconds since epoch and convert to nanoseconds
    epoch_seconds = time.to_i
    epoch_nanoseconds = epoch_seconds * 1_000_000_000

    # Add additional nanoseconds from fractional seconds
    epoch_nanoseconds += time.usec * 1000
    
    epoch_nanoseconds
  end

  def milliseconds_to_datetime(milliseconds)
    seconds = milliseconds / 1000.0
    Time.at(seconds).utc.to_datetime
  end

  # Convert a DateTime to milliseconds since the Unix epoch
  def datetime_to_milliseconds(datetime)
    (datetime.to_time.to_f * 1000).to_i
  end
end

app/models/exchange.rb
class Exchange < ApplicationRecord
  has_many :funding_rates, dependent: :destroy
end

app/models/funding_rate.rb
class FundingRate < ApplicationRecord
  belongs_to :exchange
  belongs_to :instrument
end

app/models/hyperliquid.rb
class Hyperliquid
  include NanosecondsConversion
  include HTTParty
  base_uri 'api.hyperliquid.xyz'

  def funding(instrument)
    headers = {"Content-Type" => "application/json"}
    body = { "type" => "predictedFundings" }
    self.class.post("/info", headers: headers, body: body.to_json)
  end

  def save_funding_rate(response, exchange, instrument)
    token_details = response.find { |data| data[0] == instrument.name }

    return unless token_details

    perp_data = token_details.last.find { |data| data[0] == "HlPerp" }

    FundingRate.create!(
      rate: perp_data.last["fundingRate"],
      expire_at: milliseconds_to_datetime(perp_data.last["nextFundingTime"]),
      exchange: exchange,
      instrument: instrument
    )
  end
end

app/models/instrument.rb
class Instrument < ApplicationRecord
  has_many :funding_rates

  def hourly_rate(exchange)
    time = Time.now

    funding_rate = FundingRate.where(
      exchange: exchange,
      instrument: self,
      created_at: time.beginning_of_hour..time.end_of_hour
    ).last

    funding_rate ? funding_rate.rate : 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @instruments = if params[:coin]
      Instrument.where(name: params[:coin])
    else
      Instrument.order(name: :asc)
    end
    @aevo = Exchange.find_by(name: "Aevo")
    @hyperliquid = Exchange.find_by(name: "Hyperliquid")
    @latest_funding_rate = FundingRate.order(created_at: :desc)&.first
  end
end

app/controllers/fetch_rates_controller.rb
class FetchRatesController < ApplicationController
  def create
    FetchFundingRatesService.run
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def display_rate_with_color(rate)
    return '-' if rate.nil?
    klass = rate.positive? ? 'text-green-700' : 'text-red-700'
    content_tag(:span, number_to_percentage(rate.abs * 100, precision: 4), class: klass)
  end

  def calculate_arb(rate1, rate2)
    return '-' if rate1.nil? || rate2.nil?
    display_rate_with_color(rate1 - rate2)
  end
end

app/views/dashboards/_instrument.html.erb
<% aevo_rate = instrument.hourly_rate(aevo) %>
<% hyperliquid_rate = instrument.hourly_rate(hyperliquid) %>

<tr>
  <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-white sm:pl-0">
    <%= instrument.name %>
  </td>
  <td class="whitespace-nowrap px-3 py-4 text-sm text-neutral-100">
    <%= display_rate_with_color(aevo_rate) %>
  </td>
  <td class="whitespace-nowrap px-3 py-4 text-sm text-neutral-100">
    <%= display_rate_with_color(hyperliquid_rate) %>
  </td>
  <td class="whitespace-nowrap px-3 py-4 text-sm text-neutral-100">
    <%= calculate_arb(aevo_rate, hyperliquid_rate) %>
  </td>
</tr>

app/views/dashboards/show.html.erb
<div class="my-16">

  <div class="flex justify-between">
    <section>
      <h2 class="text-4xl">Funding Comparison</h2>
      <p class="text-base mt-1">Funding rate differences across exchanges</p>
    </section>

    <section class="self-end">
      <%= button_to fetch_rate_path, class: "text-white bg-gray-800 hover:bg-gray-900 focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700" do %>
        Fetch Rates
      <% end %>
      <p class="text-xs">Updated as of: <%= local_time(@latest_funding_rate.created_at) %></p>
    </section>
  </div>

  <div class="mt-8 bg-neutral-900 border border-neutral-700 inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
    <table class="min-w-full divide-y divide-neutral-700">
      <thead>
        <tr>
          <th class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-white sm:pl-0">Instrument</th>
          <th class="px-3 py-3.5 text-left text-sm font-semibold text-white">Aevo</th>
          <th class="px-3 py-3.5 text-left text-sm font-semibold text-white">Hyperliquid</th>
          <th class="px-3 py-3.5 text-left text-sm font-semibold text-white">Aevo-HL Arb</th>
        </tr>
      </thead>
      <tbody class="divide-y divide-neutral-800">
        <% cache @instruments do %>
          <% @instruments.each do |instrument| %>
            <% cache instrument do  %>
              <%= render partial: "instrument", locals: { instrument: instrument, aevo: @aevo, hyperliquid: @hyperliquid } %>
            <% end %>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FundingComparison</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body class="bg-neutral-950 text-neutral-50">
    <div class="mx-auto max-w-7xl sm:px-6 lg:px-8">
      <%= yield %>
    </div>
  </body>
</html>